#!/bin/bash
sudo apt update -y
sudo apt install -y nginx
sudo systemctl enable nginx
sudo systemctl start nginx
sudo chmod -R a+rw /var/www
sudo echo "<h1>Hello world from Public $(hostname -f)<h1>" > /var/www/html/index.html
sudo systemctl restart nginx

